#Account info write the username of all your account
account_username:
  - "a"
#Account info write the password of all your account
account_password:
  - "z"

# Words to search for giveaway
words_to_search:
  - "giveaway"
  - "#concours"
  - "concours"
  - "#JeuConcours"
  - "JeuConcours"
  - "offre follow gagnant"
  - "concours pour gagner"
  - "gagner rt"
  - "Gagnez rt + follow"
  - "RT & follow"
  - "rt follow"
  - "concours rt like"
  - "concours rt fav"
  - "RT tweet Follow"
  - "concours rt follow"
  - "rt follow tas"
  - "rt follow tirage au sort"
  - "rt follow gagner"
  - "rt follow commente"
  - "rt suivre concours"
  - "rt suivez concours"
  - "rt suivre tirage au sort"
  - "rt suivre tas"
  - "concours remporter"
  - "remporter rt"
  - "concours tas le"
  - "concours résultats le rt"
  - "tirage au sort concours"
  - "concours résultat le rt"


# Those are the word needed on the tweet for the bot to comment but we won't lookup for a random comment to copy for those words:
word_list_to_not_check_for_copy:
  - "+ #"
  - "avec #"
  - "le #"
  
# Those are the word needed on the tweet for the bot to comment when the tweet ask to comment one thing in particular
word_list_to_check_for_special_comment:
  - "commenter avec"
  - "commentez avec"
  - "commente avec"
  - "commentez"
  - "commenter"
  - "commente"
  - "écrit"
  - "écrire"
  - "dites"
  - "répondez"
  - "réponder"
  

# Those are the word needed on the tweet for the bot to comment when the tweet ask to comment random stuff
word_list_to_check_for_comment:
  - "+ #"
  - "avec #"
  - "le #"
  - "mentionnez #"
  - "commente"
  - "commentaire"
  - "commentant"
  - "écrit"
  - "écrire"
  - "dites"
  - "cite"
  - "donne"
  - "tweet avec"
  - "tweetent avec"
  - "tweetent : avec"
  - "tweet : avec"
  - "tweet #"
  - "hashtag"
  - "répond"
  - "indique"


# The same as word_list_to_check_for_comment but for word shorter than 6 characters
short_word_list_to_check_for_comment:
  - "dit"
  - "dis"
  - "com"

# Those are the word needed on the tweet for the bot to tag one or more account
word_list_to_check_for_tag:
  - "invit"
  - "mention"
  - "tag"
  - "#tag"
  - "identif"
  - "@ un"
  - "@ une"
  - "@ des"
  - "@ tes"
  - "@ 1"
  - "@ deux"
  - "@ 2"
  - "@ plusieurs"
  
# Word list to check if we need to tag 1 account
one_poeple_list:
  
  - "@ un"
  - "@ 1"
  - "tag un"
  - "tag 1"
  - "tag ton"
  - "tag ton"
  - "tag ta"
  - "tag la"
  - "un ami"
  - "un copain"
  - "une personne"
  - "la personne"
  - "un pote"
  - "1 pote"
  - "1 ami"
  - "1 copain"
  - "1 personne"
  - "un(e) ami(e)"
  - "un.e ami.e"
  - "quelqu'un"
  - "un fan"
  - "1 fan"
  - "un(e) pote"
  - "un(e) pote"


# Word list to check if we need to tag 2 accounts
two_poeple_list:
  - "tag deux"
  - "tag 2"
  - "@ deux"
  - "@ 2"
  - "2 amis"
  - "2 ami(e)s"
  - "2 ami"
  - "2 personnes"
  - "2 potes"
  - "deux amis"
  - "deux ami(e)s"
  - "deux ami"
  - "deux personnes"
  - "deux potes"

# Word list to check if we need to tag 3 accounts or more
three_or_more_poeple_list:
  - "3 amis"
  - "3 ami(e)s"
  - "3 ami"
  - "3 personnes"
  - "3 potes"
  - "trois amis"
  - "trois ami(e)s"
  - "trois ami"
  - "trois personnes"
  - "trois potes"
  - "tes amis"
  - "des amis"
  - "tes potes"
  - "des potes"

# Accounts we want to invite you must but a space at the end of each account and a space at the	start of the first account
accounts_to_tag:
  - "@Mediavenir "
  - "@NetflixFR "
  - "@ActuFoot_ "

  
tag_more_than_three: False

# Accounts we want to invite if tag more than three is true you must but a space at the end of each account and a space at the	start of the first account
accounts_to_tag_more:
  - "@Pediavenir "
  - "@CerfiaFR "
  - "@Arkunir "



# Accounts that we don't want to follow
accounts_to_blacklist:
  - "@RealB0tSpotter"
  - "@jflessauSpam"
  - "@b0ttem"
  - "@BotSpotterBot"
  - "@gulzaarAvi"
  - "@BotFett"
  - "@ElChap0420"
  - "@RealB0tSpotter"
  - "@YNTF"
  - "@0xCryptax"
  - "@0xHaz666"
  - "@0xMakeMoney"
  - "@AGoldboxDeals"
  - "@BestConcourss"
  - "@BlackPromos"
  - "@BrownConcours"
  - "@buuuffNFT"
  - "@ChrisGeekWorld"
  - "@ConcoursYoko"
  - "@Croissant_NFA"
  - "@cryptogmznft"
  - "@destyy657"
  - "@drakebil22"
  - "@Eks74326603"
  - "@FailsDrole"
  - "@oxyGiveaway"
  - "@GarwyNFT"
  - "@GreyConcours"
  - "@LAGAMINGROOM"
  - "@levraizarkx"
  - "@lofi_feeling"
  - "@MkNFTz"
  - "@MONSIEURCHOUYTB"
  - "@MONSIEURCHOYTB"
  - "@NeyaGiveaway"
  - "@nftconcours"
  - "@simmessier"
  - "@NigmoInft"
  - "@Nigmolnft"
  - "@PolinskiNFT"
  - "@slconcours"
  - "@SPIDEReGAMES"
  - "@SPIFLY"
  - "@THE_CALENDRIER"
  - "@teoconcours"
  - "@timgiveway"
  - "@ToutgagnerCom"
  - "@wayzeeth"
  - "@wsconcours"
  - "@Zarkxlevraii"
  - "@cybervictimes"
  - "@zarkxnft"
  - "@ZetroxEu"
  - "@sim_messier"
  - "@BakoruDeFi"
  - "@YuwyNFT"
  - "@Mr_Rinos"
  - "@corteiz_reps"
  - "@concours_quiz"
  - "@lagamoujeth"
  - "@pormakino"
  - "@WRN2006FRR"
  - "@wrn2006fr"
  - "@AsyaGiveaway"
  - "0xNFTgiveaway"
  - "@cineplus"
# Sentences that the bot will say to act not like a bot
setence_to_tweet:
  - "L'avenir appartient à ceux qui croient en la beauté de leurs rêves."
  - "L'échec est la fondation de la réussite."
  - "Chaque jour est une occasion de recommencer."
  - "La vie est un voyage, pas une destination."
  - "Le bonheur est un choix."
  - "La patience est une vertu."
  - "L'optimisme est la clé du succès."
  - "Les erreurs sont la preuve que nous essayons."
  - "La persévérance paie toujours."
  - "L'amour est plus fort que la haine."
  - "La vérité sort toujours du fond de l'âme."
  - "La confiance en soi est la clé de la réussite."
  - "La persévérance est la mère de la réussite."
  - "Le temps guérit toutes les blessures."
  - "L'espoir est l'antidote de la dépression."
  - "La créativité est la clé de la réussite."
  - "Les petits plaisirs de la vie sont les meilleurs."
  - "L'amitié est un trésor précieux."
  - "La vie est ce que vous en faites."
  - "L'éducation est la clé du succès."
  - "La vie est courte, profitez-en."
  - "La sagesse vient avec l'âge."
  - "La grâce est la plus grande force de la nature."
  - "La beauté est dans les yeux de celui qui regarde."
  - "La simplicité est la clé de la vie."
  - "La vie est un cadeau, ne le gaspillez pas."
  - "La compassion est la plus grande vertu de l'homme."
  - "L'amour est le plus grand pouvoir du monde."
  - "Le temps est précieux, ne le gaspillez pas."
  - "La curiosité est le moteur de la découverte."
  - "L'espoir est le moteur de la vie."
  - "La générosité est la plus grande vertu de l'humanité."
  - "La vie est un jeu, jouez-le à fond."
  - "La vie est belle, appréciez-la."
  - "La vie est un défi, relevez-le."
  - "La vie est un choix, choisissez-la avec sagesse."
  - "La vie est une danse, dansez-la avec joie."
  - "La vie est un don, soyez reconnaissant."
  - "La vie est une aventure, soyez audacieux."
  - "La vie est un voyage, profitez-en."
  - "La vie est un roman, écrivez-le avec passion."
  - "La vie est un cadeau, célébrez-la."
  - "La vie est un miracle, appréciez"
  - "La tolérance est la clé de la paix."
  - "La détermination est la clé de la réussite."
  - "L'entraide est la clé de la solidarité."
  - "La vie est une occasion unique, saisissez-la."
  - "L'honnêteté est la base d'une bonne relation."
  - "La vie est un chemin, suivez-le avec courage."
  - "La gratitude est la clé du bonheur."
  - "Génial :)"
  - "c'est parti !"
  - "qui ne tente rien n'a rien :p"
  - "Allez zou"
  - "Here we go"
  - "On y croit :o"
  - "Je tente ce concour"
  - "j'adore les cadeaux :p"
  - "go go go"
  - "je kiffe donc je tente"
  - "Merci à vous, c'est top"
  - "On y croit !"
  - "zoouu !"
  - "je joue ^^"
  - "Je tente on sait jamais !"
  - "j'y crois à mort"
  - "goooo ! :D"
  - "Je joue :)"
  - "allez je tente le concours"
  - "Que la chance soit avec moi"
  - "Que la chance me sourit :)"
  - "Allez là, j'y crois"
  - "hello, je joue, merci à vous"
  - "Allez c'est pour moi"
  - "l'espoir fait vivre"
  - "je commente même si je fais surement pas gagner"

# Sentences you need to tweet to invite a friend you must but a space at the end of each sentence
sentence_for_tag:
  - "J'invite : "
  - "Merci ! je tag : "
  - "Je tag : "
  - "Hop Hop, j'invite : "
  - "Avec moi : "
  - "Help me : "
  - "Pour vous aussi les gars : "
  - "tentez votre chance ! "
  - "Je tente ma chance ! J'espère que je vais gagner ! "
  - "J'espère que vais gagner ! "
  - "Merci pour le concours ! Essayez aussi : "
  - "Que la chance soit avec moi ! et vous "
  - "Merci d'organiser ce concours ! Ça peut vous intéresser "
  - "On croise les doigts ! vous aussi "
  - "C'est pour vous ça ! : "
  - "Celui là on le gagne"
  - "J'espère que vais gagner ! On participe ! "
  - "Merci d'organiser ce concours ! "
  - "Bonne chance à tous ! "
  - "J'adore les concours et je sais que vous aussi "
  - "J'ai tellement envie de gagner, essayez vous aussi "
  - "Je participe et j'invite "
  - "Bonjour je participe avec plaisir. Merci pour ce concours et bonne journée ! "
  - "Merci beaucoup j'adore votre compte. Je vous souhaite une belle continuation. J'invite "
  - "Bonjour je participe avec plaisir à ce super concours et j'invite "
  - "Superbe ! Je tente ma chance bien volontiers et j'invite "
  - "Chouette bonjour je participe avec plaisir avec "
  - "Bonjour je tente ma chance avec "
  - "Bonjour, Je tente ma chance bien volontiers et j'invite "
  - "Merci beaucoup pour ce super concours, je tague "
  - "Bonjour génial ! Je tente ma chance et j'identifie "
  - "Merci ! J'invite "
  - "Hello !!! Merci beaucoup je tente ma chance merci et bonne journée ! Je tague "
  - "Bonjour je participe avec plaisir pour ce beau cadeau et j'invite "
  - "Bonjour et merci pour ce super concours :) j'invite "
  - "Bonjour, trop Sympa ce concours. Essayez-vous aussi "
  - "Je tag mes amis "
  - "On tente encore et encore "
  - "Je tente ma chance aux côtés de "
  - "Ça vous intéressent ? "
  - "Qu'est ce que vous en pensez ? Allez participez-vous aussi "
  - "Let's go, je suis sûr qu'on va gagner cette fois :) "

# Sentences you need to tweet when you need to do a comment but don't need to invite friend you must but a space at the end of each sentence
sentence_for_random_comment:
  - "Merci ! "
  - "Je participe "
  - "Hop Hop "
  - "Que la force soit avec moi "
  - "Je tente ma chance ! J'espère que je vais gagner ! "
  - "J'espère que vais gagner ! "
  - "Merci pour le concours ! "
  - "Que la chance soit avec moi ! "
  - "Merci d'organiser ce concours ! "
  - "On croise les doigts ! "
  - "C'est pour moi ça ! "
  - "Celui là on le gagne"
  - "J'espère que vais gagner ! Je participe ! "
  - "Merci d'organiser ce concours ! "
  - "Bonne chance à tous ! "
  - "J'adore les concours et surtout celui si "
  - "J'ai tellement envie de gagner "
  - "Bonjour je participe avec plaisir. Merci pour ce concours et bonne journée ! "
  - "Merci beaucoup pour j'adore votre compte. Je vous souhaite une belle continuation "
  - "Bonjour je participe avec plaisir à ce super concours "
  - "Superbe ! Je tente ma chance bien volontiers "
  - "Chouette bonjour je participe avec plaisir "
  - "Bonjour je tente ma chance "
  - "Bonjour, Je tente ma chance bien volontiers "
  - "Merci beaucoup pour ce super concour "
  - "Bonjour génial ! Je tente ma chance "
  - "Hello !!! Merci beaucoup je tente ma chance "
  - "Bonjour je participe avec plaisir pour ce beau cadeau "
  - "Bonjour et merci pour ce super concours :) "
  - "Bonjour, trop Sympa ce concours. "
  - "On tente encore et encore "
  - "Je tente ma chance même si je risque de ne pas gagner "
  - "Ça vous intéressent ? "
  - "Let's go, je suis sûr qu'on va gagner cette fois :) "

# hashtag we don't want to tweet
hashtag_to_blacklist:
  - "giveaway"
  - "concours"
  - "rt"
  - "follow"
  - "jeuconcours"
  - "jeu"
  - "jeux"
  - "cadeau"
  - "cadeaux"
  - "concour"
  - "giveway"
  - "tweet"
  - "commente"
  - "followers"
  - "follower"
  - "twitter"
  - "tag"
  - "jeuxconcours"
  - "giveawayalert"
  - "retweet"
  - "mentionne"
  - "kdo"
  - "gratuit"
  - "cadeaunoel"
  - "annonce"
  - "noel"
  - "joyeuxnoel"

# We don't want to participate in giveaway with these words
giveaway_to_blacklist:
  - "nude"
  - "anal"
  - "sex"
  - "sorare"
  - "freebet"
  - "formation"
  - "dvd"
  - "mint"
  - "freemint"
  - "film"
  - "cinéma"
  - "ebook"
  - "gode"
  

# If headless is set to True the bot won't open a chrome windows while doing giveaways otherwise it will
headless: True

#Add your own flux rss those will be used to make tweet after doing giveaway
flux_rss:
  - "https://www.france24.com/fr/rss"
  - "https://www.france24.com/fr/europe/rss"
  - "https://www.france24.com/fr/france/rss"
  - "https://www.france24.com/fr/afrique/rss"
  - "https://www.france24.com/fr/moyen-orient/rss"
  - "https://www.france24.com/fr/am%C3%A9riques/rss"
  - "https://www.france24.com/fr/asie-pacifique/rss"
  - "https://www.france24.com/fr/%C3%A9co-tech/rss"
  - "https://www.france24.com/fr/sports/rss"
  - "https://www.france24.com/fr/culture/rss"
  - "https://www.france24.com/fr/plan%C3%A8te/rss"

# If copy is set to True the bot will copy comment to have way better comment overall
copy: True

#If forever_loop is set to true the bot will run forever otherwise it will run once
forever_loop: False

#The minimum time to wait in second beetween each follow, giveaway done (Like,Retweet,Comment if needed) , random tweet, random retweet the bot will choose a random time beetween min and max time
min_time: 45
#If this option is set to true the bot will make a sleep of 1H30 every 10 giveaways to act more human
human: False

#The maximum time to wait in second beetween each follow, giveaway done (Like,Retweet,Comment if needed) , random tweet, random retweet the bot will choose a random time beetween min and max time
max_time: 300
#If the bot crashed and you want to redo the giveaway you where doing just set the value to true
crash_or_no: False

#If the option is set to False the bot will only @ account withouth the sentence when he need to
add_sentence_to_tag: True

#If random is set to true the bot will do even more random action: It will do a random number of retweet and tweet beetween 1 and random_tweet_nb and random_retweet_nb and it will comment withouth sentence on random time
random_action: False

# If the value is set to true the bot will make random retweet and tweet
random_retweet_and_tweet: True

# If the value is set to true the bot will search and rt random tweet based on word_to_rt list
rt_your_word: False

# Word to this list will be used to rt random tweet
word_to_rt:
  - "football"
  - "musique"
  - "cinema"
  
# If those words are on the tweet to rt the bot won't rt the tweet

rt_to_blacklist:
  - "jeuxconcours"
  - "concours"

#If the option is set to True the bot will add # to comment other he won't
add_hashtag_to_comment: True

# If the value is set to true the bot will make random retweet and tweet
random_retweet_and_tweet: True

# The number of random tweet to do (to make this work only if your account is new otherwise you can skip it you need to make a tweet and accept twitter circle once and then it will work) 
random_tweet_nb: 5

# The number of random retweet to do
random_retweet_nb: 5

# The language of the tweet to search fr,en etc put any if you want to search tweet in any language
tweet_lang: "fr"

# Maximum number of giveaway retrieve for each word
max_giveaway: 100

# Minimum of like the tweet must have
minimum_like: 100

# Minimum of reetweet the tweet must have
minimum_rt: 200

#Maximum day for a giveaway to be done
maximum_day: 7

#Number of giveaway the bot can do
nb_of_giveaway: 30